### ISSUE TITLE
Is is possible to intercept the headers of a request?

### ISSUE THREAD

**Issue by TimGuendel** [yisibell/nuxt-proxy-request#3]
Hello,

With [http-proxy-middleware](https://github.com/chimurai/http-proxy-middleware) I was able to intercept headers of a request and change them before sending them in the proxy. Unfortunately, http-proxy-middleware does not work in prod mode with Nuxt 3.7.2, so I stumled upon this module here.

Can I achieve the same with nuxt-proxy-request?

👋

**Comment by yisibell** [comment]
Sure! Using ``

**Comment by yisibell** [comment]
Sure! Just use `configureProxyRequest` option:

```ts
export default defineNuxtConfig({
  modules: [
    'nuxt-proxy-request'
  ],
  proxy: {
    options: [
      {
        target: 'http://www.example.com',
        pathFilter: ['/api/**'],
        pathRewrite: {
          '^/api': ''
        },

        // the param `event` is H3Event
         configureProxyRequest(event) {
              // return your custom options of proxyRequest
              return {
                headers: {
                   // Add some req headers
                }
              }
         }
         
        }
    ]
  }

})
```

more details pls see [h3-proxy](https://github.com/yisibell/h3-proxy)

**Comment by yisibell** [comment]
Do not use any imports, as in `nuxt-proxy-request`, the function type option is only copied from the source code.

```ts
import foo from 'foo'

{
 configureProxyRequest(event) {
   const someValue = foo() // Invalid, an error will be reported.
  return {
    // ...
  }
 }
}
```

**Comment by TimGuendel** [comment]
I am not sure how to implement this. This is how I used to do it. How to I conditionally add headers?

`const apiProxyMiddleware = createProxyMiddleware({
    // [...]
    on: {
        proxyReq: (proxyReq, req, res) => {
            const token = getToken();
            if (token) {
                proxyReq.setHeader('token', token);
            }
        },
    }
})`

🤔

**Comment by TimGuendel** [comment]
I tried that, but this error shows up:

![image](https://github.com/yisibell/nuxt-proxy-request/assets/143795105/a4cf940d-8f55-42de-8a38-6c4199d65c3d)

**Comment by yisibell** [comment]
> I tried that, but this error shows up:
> 
> ![image](https://user-images.githubusercontent.com/143795105/270613845-a4cf940d-8f55-42de-8a38-6c4199d65c3d.png)

Implement this part inside the `configureProxyRequest`  function.

```ts
const token = getToken()
```
Due to the use of `JSON. stringify`, the code was only copied.

**Comment by TimGuendel** [comment]
I did not even call getToken(). The error happens with your example code:

```
                configureProxyRequest(event) {
                    const headers = event.node.req.headers

                    console.log(headers) //Existing `headers`

                    // some logic...

                    return {
                        headers: {
                            token: 'set here'
                        }
                    }
                }
```

**Comment by yisibell** [comment]
> I did not even call getToken(). The error happens with your example code:
> 
> ```
> configureProxyRequest(event) {
>     const headers = event.node.req.headers
> 
>     console.log(headers) //Existing `headers`
> 
>     // some logic...
> 
>     return {
>         headers: {
>             token: 'set here'
>         }
>     }
> }
> ```

There is indeed a problem. I will fix it as soon as possible, or you can directly use 'h3-proxy'.

**Comment by TimGuendel** [comment]
How do I use h3-proxy with Nuxt? I tried with a plugin, but I am getting errors with this:

`nuxtApp.vueApp.use(eventHandler(proxyEventHandler));`

**Comment by yisibell** [comment]
> I tried that, but this error shows up:
> 
> ![image](https://user-images.githubusercontent.com/143795105/270613845-a4cf940d-8f55-42de-8a38-6c4199d65c3d.png)

I had fixed it in `v1.7.0`

```ts
{
      configureProxyRequest: function (event) {
          console.log(event.node.req.headers)
          return {
            headers: {
              token: 'set some token value',
            },
          }
        },
}
```

retry above code.

**Comment by TimGuendel** [comment]
With 1.7.0 I am getting this:

```
[nitro 09:46:08]  ERROR  RollupError: 'import' and 'export' may only appear at the top level (Note that you need plugins to import files that are not JavaScript)

 8:         const runtimeOptions = [].concat(useRuntimeConfig().proxy?.options)[0 ?? 0]
 9:
10:         export default createProxyMiddleware(defu(runtimeOptions, buildtimeOptions))
            ^
✔ Nitro built in 563 ms
```

**Comment by yisibell** [comment]
> With 1.7.0 I am getting this:
> 
> ```
> [nitro 09:46:08]  ERROR  RollupError: 'import' and 'export' may only appear at the top level (Note that you need plugins to import files that are not JavaScript)
> 
>  8:         const runtimeOptions = [].concat(useRuntimeConfig().proxy?.options)[0 ?? 0]
>  9:
> 10:         export default createProxyMiddleware(defu(runtimeOptions, buildtimeOptions))
>             ^
> ✔ Nitro built in 563 ms
> ```
> 
> show me your code.
pls show me your code.

**Comment by TimGuendel** [comment]
```
    proxy: {
        options: [
            {
                target: process.env.BACKEND_URL as string,
                pathFilter: ['/api/**'],
                pathRewrite: {
                    '^/api': ''
                },
                configureProxyRequest: function (event) { // Do not use `configureProxyRequest() {}`
                    console.log(event.node.req.headers)
                    return {
                        headers: {
                            token: 'set some token value',
                        },
                    }
                },
            }
        ]
    },
```

**Comment by yisibell** [comment]
> ```
>     proxy: {
>         options: [
>             {
>                 target: process.env.BACKEND_URL as string,
>                 pathFilter: ['/api/**'],
>                 pathRewrite: {
>                     '^/api': ''
>                 },
>                 configureProxyRequest: function (event) { // Do not use `configureProxyRequest() {}`
>                     console.log(event.node.req.headers)
>                     return {
>                         headers: {
>                             token: 'set some token value',
>                         },
>                     }
>                 },
>             }
>         ]
>     },
> ```

remove the explanatory note `// Do not use `configureProxyRequest() {}``

**Comment by yisibell** [comment]
> How do I use h3-proxy with Nuxt? I tried with a plugin, but I am getting errors with this:
> 
> `nuxtApp.vueApp.use(eventHandler(proxyEventHandler));`

See https://github.com/yisibell/h3-proxy#nuxt
